#General Configuration
DATALOADER_NUM_WORKERS: 4
DATASET:
  DATASET_2D: /home/lambda1/Documents/JARVIS-HybridNet/datasets/3D_12Cam
  DATASET_3D: /home/lambda1/Documents/JARVIS-HybridNet/datasets/3D_12Cam
CENTERDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 4
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 50
  CHECKPOINT_SAVE_INTERVAL: 10
  IMAGE_SIZE: 320
KEYPOINTDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 4
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 100
  CHECKPOINT_SAVE_INTERVAL: 10
  BOUNDING_BOX_SIZE: 320
  NUM_JOINTS: 23
HYBRIDNET:
  BATCH_SIZE: 1
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 50
  CHECKPOINT_SAVE_INTERVAL: 10
  NUM_CAMERAS: 3
  ROI_CUBE_SIZE: 208
  GRID_SPACING: 2
