#General Configuration
DATALOADER_NUM_WORKERS: 4       #Number of threads used for dataloading

#Dataset Configuration
DATASET:
  DATASET_2D: Example_Dataset   #2D dataset path (usually same as DATASET_3D)
  DATASET_3D: Example_Dataset   #3D dataset path

#EfficientTrack 2D Center Detector Configuration:
CENTERDETECT:
  MODEL_SIZE: 'small'           #Can be 'small', 'medium' or 'large'
  BATCH_SIZE: 8                 #Set to 4 for very small datasets (<500 Frames) 
  MAX_LEARNING_RATE: 0.01       #Max learning rate in OneCycle schedule
  NUM_EPOCHS: 50                #Set to 100 for very small datasets
  CHECKPOINT_SAVE_INTERVAL: 10  #Saves a .pth checkpoint ever N epochs
  IMAGE_SIZE: 256               #Frames get resized to NxN

#EfficientTrack 2D Keypoint Detector Configuration
KEYPOINTDETECT:
  MODEL_SIZE: 'small'           #Can be 'small', 'medium' or 'large'
  BATCH_SIZE: 8                 #Set to 4 for very small datasets (<500 Frames) 
  MAX_LEARNING_RATE: 0.01       #Max learning rate in OneCycle schedule
  NUM_EPOCHS: 100               #Set to 200 for very small datasets
  CHECKPOINT_SAVE_INTERVAL: 10  #Saves a .pth checkpoint ever N epochs
  BOUNDING_BOX_SIZE: 256        #Size of the crop around the subject that gets 
                                # fed into KeypointDetect
  NUM_JOINTS: 23                #Number of keypoints (Don't change!)

#hybridNet Configuration
HYBRIDNET:
  BATCH_SIZE: 1                 #Currently only batch size 1 is supported
  MAX_LEARNING_RATE: 0.003      #Max learning rate in OneCycle schedule
  NUM_EPOCHS: 30                #Set to 60 for very small datasets (<500 Frames)
  CHECKPOINT_SAVE_INTERVAL: 10  #Saves a .pth checkpoint ever N epochs
  NUM_CAMERAS: 12               #Number fo cameras (Don't change!)
  ROI_CUBE_SIZE: 144            #Size of the 3D bounding box in mm 
  GRID_SPACING: 2               #Resolution of the 3D bounding box in mm 

KEYPOINT_NAMES:                 #List of all keypoint names (for visualization)
- Pinky_T
- Pinky_D
- Pinky_M
- Pinky_P
- Ring_T
- Ring_D
- Ring_M
- Ring_P
- Middle_T
- Middle_D
- Middle_M
- Middle_P
- Index_T
- Index_D
- Index_M
- Index_P
- Thumb_T
- Thumb_D
- Thumb_M
- Thumb_P
- Palm
- Wrist_U
- Wrist_R

SKELETON:                   #List of all joints (for visualization only)
- - Pinky_T
  - Pinky_D
- - Pinky_D
  - Pinky_M
- - Pinky_M
  - Pinky_P
- - Ring_T
  - Ring_D
- - Ring_D
  - Ring_M
- - Ring_M
  - Ring_P
- - Middle_T
  - Middle_D
- - Middle_D
  - Middle_M
- - Middle_M
  - Middle_P
- - Index_T
  - Index_D
- - Index_D
  - Index_M
- - Index_M
  - Index_P
- - Thumb_T
  - Thumb_D
- - Thumb_D
  - Thumb_M
- - Thumb_M
  - Thumb_P
- - Pinky_P
  - Ring_P
- - Ring_P
  - Middle_P
- - Middle_P
  - Index_P
- - Index_P
  - Thumb_M
- - Index_P
  - Thumb_P
- - Pinky_P
  - Wrist_U
- - Wrist_U
  - Wrist_R
- - Wrist_R
  - Thumb_P
