#General Configuration
DATALOADER_NUM_WORKERS: 4

#Dataset Configuration
DATASET:
  DATASET_2D: Example_Dataset
  DATASET_3D: Example_Dataset

#EfficientTrack 2D  Center Detector Configuration:
CENTERDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 4
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 50
  CHECKPOINT_SAVE_INTERVAL: 10
  IMAGE_SIZE: 256

#EfficientTrack 2D Keypoint Detector Configuration
KEYPOINTDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 4
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 100
  CHECKPOINT_SAVE_INTERVAL: 1
  BOUNDING_BOX_SIZE: 256
  NUM_JOINTS: 23

#Vortex Configuration
HYBRIDNET:
  BATCH_SIZE: 1
  MAX_LEARNING_RATE: 0.02
  NUM_EPOCHS: 50
  CHECKPOINT_SAVE_INTERVAL: 1

  NUM_CAMERAS: 12
  ROI_CUBE_SIZE: 160
  GRID_SPACING: 2
