#General Configuration
DATALOADER_NUM_WORKERS: 4
USE_MIXED_PRECISION: false

#Dataset Configuration
DATASET:
  DATASET_2D: Example_Dataset
  DATASET_3D: Example_Dataset

#EfficientTrack 2D  Center Detector Configuration:
CENTERDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 8
  LEARNING_RATE: 0.001
  CHECKPOINT_SAVE_INTERVAL: 10
  IMAGE_SIZE: 320

#EfficientTrack 2D Keypoint Detector Configuration
KEYPOINTDETECT:
  COMPOUND_COEF: 0
  BATCH_SIZE: 8
  LEARNING_RATE: 0.001
  CHECKPOINT_SAVE_INTERVAL: 10
  BOUNDING_BOX_SIZE: 256

#Vortex Configuration
HYBRIDNET:
  BATCH_SIZE: 1
  LEARNING_RATE: 0.001
  CHECKPOINT_SAVE_INTERVAL: 5

  ROI_CUBE_SIZE: 160
  GRID_SPACING: 2
