#General Configuration
DATALOADER_NUM_WORKERS:

#Dataset Configuration
DATASET:
  DATASET_2D:
  DATASET_3D:

#Center Detector Configuration:
CENTERDETECT:
  COMPOUND_COEF:
  BATCH_SIZE:
  MAX_LEARNING_RATE:
  NUM_EPOCHS:
  CHECKPOINT_SAVE_INTERVAL:
  IMAGE_SIZE:

#EfficientTrack Configuration
KEYPOINTDETECT:
  COMPOUND_COEF:
  BATCH_SIZE:
  MAX_LEARNING_RATE:
  NUM_EPOCHS:
  CHECKPOINT_SAVE_INTERVAL:
  BOUNDING_BOX_SIZE:
  NUM_JOINTS:

#Vortex Configuration
HYBRIDNET:
  BATCH_SIZE:
  MAX_LEARNING_RATE:
  NUM_EPOCHS: 
  CHECKPOINT_SAVE_INTERVAL:

  NUM_CAMERAS:
  ROI_CUBE_SIZE:
  GRID_SPACING:
